CREATE TABLE IF NOT EXISTS User (
    userId INT AUTO_INCREMENT,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT userPK PRIMARY KEY(userId)
);

CREATE TABLE IF NOT EXISTS Recipe (
    quoteId INT AUTO_INCREMENT PRIMARY KEY,
    quote VARCHAR(255) NOT NULL,
    userId INT NOT NULL,
    CONSTRAINT userFK FOREIGN KEY(userId) REFERENCES User(userId)  
);